### ISSUE TITLE
set nodePort

### ISSUE THREAD

**Issue by LeoCBS** [dharmeshkakadia/presto-kubernetes#1]
Hi, you could fix presto service port using attribute nodePort,  this way you could always have the same port that you use in readme :)

```
apiVersion: v1
kind: Service
metadata:
  name: presto
spec:
  selector:
    presto: coordinator
  type: NodePort
  ports: 
    - port: 8080
      nodePort: 30005
```
